sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 学生认证弄的阿里云服务器ip：8.130.106.145
    # mysql和redis密码：Aa565034470
    # 老的试用服务器ip：39.106.77.183
    # mysql和redis密码：565034470
    host: localhost
    port: 3306
    database: mixdp
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tMHJgr6
    access-key-id1: cdhZeC4sW5hU
    access-key-secret: Hv0t8CKG2FO8I
    access-key-secret1: IR28QhHNf0FpusiRg
    bucket-name: plumsnow
  wechat:
    appid: wx6ac27855b9675112
    secret: fb1731ec91f5a8ffa5b44ab19fac3991
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    #商家资质文件，没有的啦
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    #notifyUrl是cpolar做的临时域名，每次启动都不相同
    notifyUrl: https://7cca6f5.r3.cpolar.cn/notify/paySuccess
    refundNotifyUrl: https://7cca6f5.r3.cpolar.cn/notify/refundSuccess


spring:
  redis:
    host: localhost
    port: 6379
    password: Aa565034470
    database: 1 #操作的是1号数据库
    jedis:
      #Redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #连接池最大阻塞等待时间
        max-idle: 4 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  cache:
    redis:
      time-to-live: 1800000 #设置缓存时间为1800s--30min

